spring:
  profiles:
    default: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true

storage:
  raw-files:
    path: ./data/raw

export:
  local:
    enabled: true
    path: ./data/exports
  google:
    enabled: false

pipeline:
  sample-file: sample-import.csv
  auto-run: false

api:
  key: ${API_KEY:}

google:
  application-name: finance-tracker
  sheets:
    spreadsheet-id: 1G_uvNzT8wtWGJZ3TiRSSnfHg_MspkG6bPA3AP5vjNFw
  credentials:
    path: /google-service-account.json
